package com.ar.mrm.entities;
// Generated Aug 9, 2010 2:30:11 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Profile generated by hbm2java
 */
public class Profile  implements java.io.Serializable {


     private Integer id;
     private String description;
     private Set applicants = new HashSet(0);
     private Set questions = new HashSet(0);
     private Set testModels = new HashSet(0);

    public Profile() {
    }

	
    public Profile(String description) {
        this.description = description;
    }
    public Profile(String description, Set applicants, Set questions, Set testModels) {
       this.description = description;
       this.applicants = applicants;
       this.questions = questions;
       this.testModels = testModels;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getApplicants() {
        return this.applicants;
    }
    
    public void setApplicants(Set applicants) {
        this.applicants = applicants;
    }
    public Set getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Set questions) {
        this.questions = questions;
    }
    public Set getTestModels() {
        return this.testModels;
    }
    
    public void setTestModels(Set testModels) {
        this.testModels = testModels;
    }




}


