package com.ar.mrm.entities;
// Generated Aug 9, 2010 2:30:11 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * QuestionAnswered generated by hbm2java
 */
public class QuestionAnswered  implements java.io.Serializable {


     private Integer id;
     private Question question;
     private Test test;
     private boolean correct;
     private Set optionChoseds = new HashSet(0);

    public QuestionAnswered() {
    }

	
    public QuestionAnswered(Question question, Test test, boolean correct) {
        this.question = question;
        this.test = test;
        this.correct = correct;
    }
    public QuestionAnswered(Question question, Test test, boolean correct, Set optionChoseds) {
       this.question = question;
       this.test = test;
       this.correct = correct;
       this.optionChoseds = optionChoseds;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Question getQuestion() {
        return this.question;
    }
    
    public void setQuestion(Question question) {
        this.question = question;
    }
    public Test getTest() {
        return this.test;
    }
    
    public void setTest(Test test) {
        this.test = test;
    }
    public boolean isCorrect() {
        return this.correct;
    }
    
    public void setCorrect(boolean correct) {
        this.correct = correct;
    }
    public Set getOptionChoseds() {
        return this.optionChoseds;
    }
    
    public void setOptionChoseds(Set optionChoseds) {
        this.optionChoseds = optionChoseds;
    }




}


