package com.ar.mrm.entities;

import com.ar.mrm.dto.TestModelQuestionQtyDTO;
// Generated Aug 9, 2010 2:30:11 AM by Hibernate Tools 3.2.1.GA



/**
 * TestModelQuestionqty generated by hbm2java
 */
public class TestModelQuestionqty  implements java.io.Serializable {

	private static final long serialVersionUID = -5465865661423664992L;
	
	private Integer id;
     private Seniority seniority;
     private TestModel testModel;
     private Technology technology;
     private Integer qtyQuestions;
     
    public TestModelQuestionqty() {
    }

    public TestModelQuestionqty(Seniority seniority, TestModel testModel, Technology technology, int qtyQuestions) {
       this.seniority = seniority;
       this.testModel = testModel;
       this.technology = technology;
       this.qtyQuestions = qtyQuestions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Seniority getSeniority() {
        return this.seniority;
    }
    
    public void setSeniority(Seniority seniority) {
        this.seniority = seniority;
    }
    public TestModel getTestModel() {
        return this.testModel;
    }
    
    public void setTestModel(TestModel testModel) {
        this.testModel = testModel;
    }
    public Technology getTechnology() {
        return this.technology;
    }
    
    public void setTechnology(Technology technology) {
        this.technology = technology;
    }
    public Integer getQtyQuestions() {
        return this.qtyQuestions;
    }
    
    public void setQtyQuestions(int qtyQuestions) {
        this.qtyQuestions = qtyQuestions;
    }


	  public int compareTo(TestModelQuestionqty q) {
	      int order = this.technology.getDescription().compareTo(q.getTechnology().getDescription());
	  
	      return order;
	   }	


}


