package com.ar.mrm.entities;
// Generated Aug 9, 2010 2:30:11 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

/**
 * Applicant generated by hbm2java
 */
public class Applicant  implements java.io.Serializable {


     private Integer id;
     private Seniority seniority;
     private Profile profile;
     private String firstName;
     private String lastName;
     private Date birthDate;
     private Date createDate;
     private String code;
     private boolean testTaked;
     private Set<Test> tests = new HashSet<Test>(0);
     private double score=0;
     
     private Date testDate;

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Seniority getSeniority() {
        return this.seniority;
    }
    
    public void setSeniority(Seniority seniority) {
        this.seniority = seniority;
    }
    public Profile getProfile() {
        return this.profile;
    }
    
    public void setProfile(Profile profile) {
        this.profile = profile;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public boolean isTestTaked() {
        return this.testTaked;
    }
    
    public void setTestTaked(boolean testTaked) {
        this.testTaked = testTaked;
    }
    public Set<Test> getTests() {
        return this.tests;
    }
    
    public void setTests(Set<Test> tests) {
        this.tests = tests;
    }
    
    @SuppressWarnings("rawtypes")
	public double getScore() {
    	double totalScore=0;
    	Iterator testIterator = getTests().iterator();
    	while(testIterator.hasNext()){
    		Test testaux=(Test) testIterator.next();
    		totalScore=totalScore+testaux.getScore();
    	}
		return totalScore;
	}


	public Date getCreateDate() {
		return createDate;
	}


	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getTestDate() {
		return testDate;
	}

	public void setTestDate(Date testDate) {
		this.testDate = testDate;
	}
}


