package com.ar.mrm.entities;
// Generated Aug 9, 2010 2:30:11 AM by Hibernate Tools 3.2.1.GA


import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.SortedSet;
import java.util.TreeSet;

/**
 * Question generated by hbm2java
 */
public class Question  implements java.io.Serializable {


     private Integer id;
     private Seniority seniority;
     private Profile profile;
     private Technology technology;
     private String description;
     private Set tests = new HashSet(0);
     private Set questionAnswereds = new HashSet(0);
     private Set<Option> options = new HashSet<Option>();

    public Question() {
    }

	
    public Question(String description) {
        this.description = description;
    }
    public Question(Seniority seniority, Profile profile, Technology technology, String description, Set tests, Set questionAnswereds, Set<Option> options) {
       this.seniority = seniority;
       this.profile = profile;
       this.technology = technology;
       this.description = description;
       this.tests = tests;
       this.questionAnswereds = questionAnswereds;
       this.options = options;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Seniority getSeniority() {
        return this.seniority;
    }
    
    public void setSeniority(Seniority seniority) {
        this.seniority = seniority;
    }
    public Profile getProfile() {
        return this.profile;
    }
    
    public void setProfile(Profile profile) {
        this.profile = profile;
    }
    public Technology getTechnology() {
        return this.technology;
    }
    
    public void setTechnology(Technology technology) {
        this.technology = technology;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getTests() {
        return this.tests;
    }
    
    public void setTests(Set tests) {
        this.tests = tests;
    }
    public Set getQuestionAnswereds() {
        return this.questionAnswereds;
    }
    
    public void setQuestionAnswereds(Set questionAnswereds) {
        this.questionAnswereds = questionAnswereds;
    }


	public Set<Option> getOptions() {
		return options;
	}

	public void setOptions(Set<Option> options) {
		this.options = options;
	}

}


