package com.ar.mrm.entities;
// Generated Aug 9, 2010 2:30:11 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Technology generated by hbm2java
 */
public class Technology  implements java.io.Serializable {


     private Integer id;
     private String description;
     @Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Technology other = (Technology) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	private Set questions = new HashSet(0);
     private Set testModelQuestionqties = new HashSet(0);
     private Set techScores = new HashSet(0);

    public Technology() {
    }

    public Technology(String description, Set questions, Set testModelQuestionqties, Set techScores) {
       this.description = description;
       this.questions = questions;
       this.testModelQuestionqties = testModelQuestionqties;
       this.techScores = techScores;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Set questions) {
        this.questions = questions;
    }
    public Set getTestModelQuestionqties() {
        return this.testModelQuestionqties;
    }
    
    public void setTestModelQuestionqties(Set testModelQuestionqties) {
        this.testModelQuestionqties = testModelQuestionqties;
    }
    public Set getTechScores() {
        return this.techScores;
    }
    
    public void setTechScores(Set techScores) {
        this.techScores = techScores;
    }




}


