package com.ar.mrm.entities;

import java.text.DecimalFormat;
import java.text.NumberFormat;


// Generated Aug 9, 2010 2:30:11 AM by Hibernate Tools 3.2.1.GA



/**
 * TechScore generated by hbm2java
 */
public class TechScore  implements java.io.Serializable {


     private Integer id;
     private Test test;
     private Technology technology;
     private double score;
     private int questionsCorrect;
     private int questions;

    public TechScore() {
    }

    public TechScore(Test test, Technology technology, double score, int questionsCorrect, int questions) {
       this.test = test;
       this.technology = technology;
       this.score = score;
       this.questionsCorrect = questionsCorrect;
       this.questions = questions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Test getTest() {
        return this.test;
    }
    
    public void setTest(Test test) {
        this.test = test;
    }
    public Technology getTechnology() {
        return this.technology;
    }
    
    public void setTechnology(Technology technology) {
        this.technology = technology;
    }
    public double getScore() {
        return this.score;
    }
    
    public void setScore(double score) {
        this.score = score;
    }
    public int getQuestionsCorrect() {
        return this.questionsCorrect;
    }
    
    public void setQuestionsCorrect(int questionsCorrect) {
        this.questionsCorrect = questionsCorrect;
    }
    public int getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(int questions) {
        this.questions = questions;
    }

    public String getFormattedScore() {
    	return new DecimalFormat("0.00%").format(this.score); 
    }


}


