package com.ar.mrm.entities;
// Generated Aug 9, 2010 2:30:11 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TestModel generated by hbm2java
 */
public class TestModel  implements java.io.Serializable {


     private Integer id;
     private Seniority seniority;
     private Profile profile;
     private Set testModelQuestionqties = new HashSet(0);
     private Set tests = new HashSet(0);
     private Integer minutesToFinish;
     
    public TestModel() {
    }

	
    public TestModel(Seniority seniority, Profile profile) {
        this.seniority = seniority;
        this.profile = profile;
    }
    public TestModel(Seniority seniority, Profile profile, Set testModelQuestionqties, Set tests,Integer minutesToFinish) {
       this.seniority = seniority;
       this.profile = profile;
       this.testModelQuestionqties = testModelQuestionqties;
       this.tests = tests;
       this.minutesToFinish = minutesToFinish;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Seniority getSeniority() {
        return this.seniority;
    }
    
    public void setSeniority(Seniority seniority) {
        this.seniority = seniority;
    }
    public Profile getProfile() {
        return this.profile;
    }
    
    public void setProfile(Profile profile) {
        this.profile = profile;
    }
    public Set<TestModelQuestionqty> getTestModelQuestionqties() {
        return this.testModelQuestionqties;
    }
    
    public void setTestModelQuestionqties(Set testModelQuestionqties) {
        this.testModelQuestionqties = testModelQuestionqties;
    }
    public Set getTests() {
        return this.tests;
    }
    
    public void setTests(Set tests) {
        this.tests = tests;
    }


	public Integer getMinutesToFinish() {
		return minutesToFinish;
	}


	public void setMinutesToFinish(Integer minutesToFinish) {
		this.minutesToFinish = minutesToFinish;
	}




}


